### PR TITLE
2.3.1 code

### PR DESCRIPTION
**Pull request by ojousima**
Tag is not connectable by default, but is connectable for 30 seconds:
 - after boot
 - after button press
 - after NFC read

Consumes 26 uA on average.

### CODE REVIEW

**Review by DG12 — CHANGES_REQUESTED** [review]
main.c 
1) You should remove comment at the beginning regarding Version 2.2.3

Following is considered redundant to invalid values present in format RAWv2 (code 05) by myself!
+++++++++++++++++++++++++++++++++++

> 2) Reconsider transmitting the "I did bad" (format 13) packets. Consider the "usual" case where nRF_LOG is unavailable (either not compiled in no dev kit available) and nfc is not close.


+++++++++++++++++++++++++++++++++++

**Comment by ojousima** [comment]
main.c: 
1) Thanks, I'll remove it. 
2) There is already a sequence of LED blinks which tells that there was a problem. Maybe the error code could be in device name scan response, i.e "RuuviABCD" -> "Err: AE" for "error in acceleration, error in environmental"? This would leave the initial packets as valid data.

**Comment by DG12** [comment]
2) LED are only visible with enclosure open and tag in view.

Following is considered redundant to invalid values present in format RAWv2 (code 05) by myself!
+++++++++++++++++++++++++++++++++++

> The idea behind "I did bad" packets is that the process receiving packets would be able to notice that something has gone wrong. Using the 13 (unlucky) format code would be ignored by normal processing unless watched for but as I formatted the packet "just like" the 03 format the process could  accept both 03 and 13 formats, stuff the data downstream and let the analysis process decide what to do.
> 
> How about this:
> ```
> if ( send_failure_packets) // default false , settable in source or by nfc (ToDo)
> {
>  snprintf( &url_buffer[8],9 , "#bad%x04x",init_status);
>     bluetooth_set_eddystone_url(url_buffer, sizeof(url_buffer) );
>     nrf_delay_ms(600u); // keep sending URL error packet for a while
>    data_buffer[0]   =   0x13 ;  
> ...
>  bluetooth_set_manufacturer_data(data_buffer, sizeof(data_buffer));
>   nrf_delay_ms(4000u); // keep sending init_stat for a while
> )
> ```

++++++++++++++++++++++++++++++++++++
3) Talk to me more about device name scan response.

4) Please give much longer connectable time a thought like 5 minutes.? (Gosh another nfc configuration item!)

**Comment by ojousima** [comment]
2. Selecting the data format by a compile-time flag would be a nice feature, I'll add selection between RAWv1 and RAWv2 after this update. RAWv2 already has error values built in. 
Most of the users will have case open at boot after software update and LEDs are visible even through the enclosure when they're on for longer periods than few milliseconds of CPU activity. Only case where user would not see the LEDs is if they enter the DFU mode through NFC and then buttonless DFU service and do not look at the enclosure after the update. The case is so rare that extra complexity in code and functionality probably causes more errors. 

3. The BLE advertisement is split in 2 parts during connectable mode: Advertising (data) and scan response which is sent to device actively requesting it. Right now the scan response has device name "RuuviABCD" and UUID of Nordic UART Service. The device name is visible to any bluetooth scanner which displays connectable devices, such as Bluetooth headphones, speakers, mice etc.

4. The 30 seconds is only for creating the connection. During this window the advertising is a lot faster, leading to increased power consumption. The connection can be held up after those 30 seconds, and 30 seconds is plenty of time for an user to connect to the tag.

**Comment by DG12** [comment]
2) I somehow missed the update which added error/invalid values to  RAWv2 ie format code 05.
Although I don't see the code actually using the error values!
3) Thanks for clearing that up. Where in the code is this?

**Pull request merged**
