### PR TITLE
2.4.2: Fix transmission interval after error detected on boot

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by DG12** [comment]
nit: 
NRF_LOG_INFO("Rebooting\r\n") should be 
NRF_LOG_WARNING("Rebooting\r\n")

**Comment by ojousima** [comment]
Yeah, and the VBAT print should be debug rather than info.

**Comment by DG12** [comment]
1)  **There should actually be a separate change log to contain such**
SUMMARY information.
**The git commit systems keeps track of**
the exact code changes (both significant and insignificant ( like removing spaces or reformatting).

Once a file is downloaded it's generation will get lost if it is no longer connected to git.

2) Regarding Wait for sensors to take first sample : 1.000 seconds is not sufficient if main_loop_interval is > 1.000 seconds. Best to not use literal constants for this.

**Comment by ojousima** [comment]
1. Yes, that's worded better. 
2. main_loop_interval and sensor delay are unrelated, as the sensors run on their own clocks after initialization. It would be a lot cleaner to have the constant defined for sure.

**Comment by DG12** [comment]
Actually, considering pull request 152,  main_loop_interval (note lowercase and lack of qualifier for various modes) is (slightly) variable.

**Pull request merged**
