### PR TITLE
Added nfc_record_url example

### PR DESCRIPTION
**Pull request by mdxs**
Example application: NFC type 2 tag with URI message for RuuviTag. Based on the examples/nfc/record_url example in the nRF5 SDK. Mixed with power management from the ruuvi_firmware example.

### CODE REVIEW

**Comment by mdxs** [comment]
Please hold on merging, most likely there is a flaw causing continues reset; that still allows the NFC tag to function, but it probably only does so in the reset cycle and may cause side effects...

**Comment by ojousima** [comment]
NFC has been on our todo for a long while anyway, I'll take a closer look to this

**Comment by ojousima** [comment]
The WIP version of NFC driver is at https://github.com/ojousima/ruuvitag_fw/tree/v1-backports , I'll wrap it up in the next few days unless something surprising comes up. 
I'll add field for URL and make it configurable in some #define.

**Comment by ojousima** [comment]
Please check the #72 , it has NFC Record text example integrated. I think it should be pretty easy to convert to record URI example if necessary.

**Comment by ojousima** [comment]
Any update on this?
Is the PR still relevant?

**Comment by ojousima** [comment]
Closing as stale

**Pull request closed without merging**
