### PR TITLE
Add licensing details

### PR DESCRIPTION
**Pull request by ojousima**
Clarifies relation, origin and licensing of various parts of the codebase. 
We have previously asked @DG12, @frawau, @laurijamsa, @ojousima if BSD-3 is ok and @jrosberg has included BSD-3 in the header. These are already listed as BSD-3.

@angst7, @dieweltistklein, @jessenic, @mdxs, @Scrin Could you comment if BSD-3 is ok license for you?

All: If you'd like to fill in or remove details such as real name and email please let me know.

### CODE REVIEW

**Review by DG12 — APPROVED** [review]
OK

**Comment by angst7** [comment]
Fine with me.

**Comment by Scrin** [comment]
BSD-3 is ok

**Comment by mdxs** [comment]
BSD-3 is ok

**Comment by jessenic** [comment]
BSD-3 is ok

**Pull request merged**
